apiVersion: v1
kind: Service
metadata:
  name: master-cluster-ip-service
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
    - name: http-port
      port: 8080
      targetPort: http-port
    - name: jnlp-port
      port: 50000
      targetPort: jnlp-port
  selector:
    app: jenkins