apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-pvc-persistent-volume-claim
  namespace: jenkins-on-minikube-ingress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

